### PR TITLE
[Do not merge] - Pgbouncer services

### PR DESCRIPTION
**Pull request by anayrat**
This PR should address #106 and other things (typo, sort services).

TODO : 

  * [x] : Doc
  * [x] : Pgbouncer stats service (just to collect stats)
  * [x] : handle when max_db_connection is not present in database section (pgbouncer use max_db_connection from default config). We must join with SHOW CONFIG
  * [x] : sometime pgbouncer clean database from show database. If we join with show pools, result is not consistent. pool are present but databases are missing.

Feature request : 

  * [x] : output without perfdata : some services provide serveral perfdata per pool or database. It generates plenty perfdatas when the cluster has hundred databases. https://github.com/OPMDG/check_pgactivity/issues/156

### CODE REVIEW

**Comment by anayrat** [comment]
Reviews are welcome!

**Comment by anayrat** [comment]
Erf, I notice pgbouncer 1.8 change columns order in statistics view. This PR can only work with pgbouncer 1.7.* :(

I wonder if we should create a separate project with dedicated functions for each view according to pgbouncer's version.
It avoid duplicated code, allow to handle different pgbouncer's versions and avoid to bloat check_pgactivity.

**Comment by frost242** [comment]
Should we close this pull request ?

**Comment by frost242** [comment]
Well, I shouldn't have asked the question, issue #106 indicates that pgbouncer support will be held in another script or project.

**Pull request closed without merging**
