### PR TITLE
password support

### PR DESCRIPTION
**Pull request by michalmedvecky**
I needed to send password as well.

### CODE REVIEW

**Comment by ioguix** [comment]
I would recommend to use a service file, with proper access rights, instead of exposing a password to the world as command argument.
Did you try with a service file ?

**Comment by michalmedvecky** [comment]
I did not, as there was no documentation for the plugin. I don't mind exposing the password as it runs on a dedicated machine only. But I understand your concern; you can add something like `($0 = "$0 @ARGV") =~ s/--password=\K\S+/x/;`

**Comment by ioguix** [comment]
As far as I can see, service files are documented on the pgsql side AND check_pga side:
* http://www.postgresql.org/docs/9.5/interactive/libpq-pgservice.html
* https://github.com/OPMDG/check_pgactivity/blob/master/README.rst, see `-S, --dbservice SERVICE_NAME`

**Comment by ioguix** [comment]
Hi,

I'm closing this PR as there was no activity for a long time and safe workaround exists using a service file or `.pgpass`.

**Pull request closed without merging**
