### PR TITLE
Add some documentation

### PR DESCRIPTION
**Pull request by frost242**

### CODE REVIEW

**Comment by rjuju** [comment]
I just saw you added docs/index.html in this PR.  This seems redundant with http://opm.readthedocs.io/probes/check_pgactivity.html (which repository is located on https://github.com/OPMDG/opm-doc).  Or did I miss something?

**Comment by frost242** [comment]
It seems that I managed to push the index.md file directly on the main repo instead of my own fork.

I was thinking about giving check_pgactivity its own life and make it live as an independent project from OPM. The OPMDG will still control the project, but imho, check_pga should get some more audience.

**Comment by frost242** [comment]
Sorry, some modifications were pushed directly to the main repo. I mismatched my working copy with a fresh clone from the main repo.

**Comment by frost242** [comment]
I'll create the same PR coming from a specific branch. Will be easier to handle. Sorry for the noise.

**Pull request closed without merging**
